const CategoriesActionTypes = {
  EDIT_ACTIVITY_NAME: "EDIT_ACTIVITY_NAME",
  EDIT_DETAIL_NAME: "EDIT_DETAIL_NAME",
  DELETE_ACTIVITY_NAME: "DELETE_ACTIVITY_NAME",
  DELETE_DETAIL_NAME: "DELETE_DETAIL_NAME",
  REORDER_CATEGORIES: "REORDER_CATEGORIES",
  DEFAULT_CATEGORIES: "DEFAULT_CATEGORIES",
  RESTORE_CATEGORIES: "RESTORE_CATEGORIES"
};

export default CategoriesActionTypes;
