// History related
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const INTERRUPT_ACTIVITY = "INTERRUPT_ACTIVITY";
export const SAVE_ACTIVITY = "SAVE_ACTIVITY";
export const SPLIT_ACTIVITY = "SPLIT_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const DISPLAY_NOTIFICATION = "DISPLAY_NOTIFICATION";
export const PURGE_HISTORY = "PURGE_HISTORY";

// categories related
export const EDIT_ACTIVITY_NAME = "EDIT_ACTIVITY_NAME";
export const EDIT_DETAIL_NAME = "EDIT_DETAIL_NAME";
export const DELETE_ACTIVITY_NAME = "DELETE_ACTIVITY_NAME";
export const DELETE_DETAIL_NAME = "DELETE_DETAIL_NAME";
export const REORDER_CATEGORIES = "REORDER_CATEGORIES";
export const DEFAULT_CATEGORIES = "DEFAULT_CATEGORIES";

// settings related
export const CHARTS_FILTER_SWITCH = "CHARTS_FILTER_SWITCH";
export const CHARTS_FILTER_SET = "CHARTS_FILTER_SET";
export const PREV_CHARTS_FILTER = "PREV_CHARTS_FILTER";
export const NEXT_CHARTS_FILTER = "NEXT_CHARTS_FILTER";
export const CHARTS_EXCLUDE_SWITCH = "CHARTS_EXCLUDE_SWITCH";
export const ADD_CHARTS_EXCLUDE_KEY = "ADD_CHARTS_EXCLUDE_KEY";
export const DEL_CHARTS_EXCLUDE_KEY = "DEL_CHARTS_EXCLUDE_KEY";