const SettingsActionTypes = {
  TOGGLE_CHARTS_DATE_FILTER: "TOGGLE_CHARTS_DATE_FILTER",
  SET_CHARTS_FILTER_DATE_START: "SET_CHARTS_FILTER_DATE_START",
  SET_CHARTS_FILTER_DATE_END: "SET_CHARTS_FILTER_DATE_END",
  PREV_CHARTS_FILTER_DATE: "PREV_CHARTS_FILTER_DATE",
  NEXT_CHARTS_FILTER_DATE: "NEXT_CHARTS_FILTER_DATE",
  TOGGLE_CHARTS_KEY_FILTER: "TOGGLE_CHARTS_KEY_FILTER",
  ADD_CHARTS_FILTER_KEY: "ADD_CHARTS_FILTER_KEY",
  DEL_CHARTS_FILTER_KEY: "DEL_CHARTS_FILTER_KEY",
  RESTORE_SETTINGS: "RESTORE_SETTINGS"
};

export default SettingsActionTypes;
