const SettingsActionTypes = {
  CHARTS_FILTER_SWITCH: "CHARTS_FILTER_SWITCH",
  CHARTS_FILTER_SET: "CHARTS_FILTER_SET",
  PREV_CHARTS_FILTER: "PREV_CHARTS_FILTER",
  NEXT_CHARTS_FILTER: "NEXT_CHARTS_FILTER",
  CHARTS_EXCLUDE_SWITCH: "CHARTS_EXCLUDE_SWITCH",
  ADD_CHARTS_EXCLUDE_KEY: "ADD_CHARTS_EXCLUDE_KEY",
  DEL_CHARTS_EXCLUDE_KEY: "DEL_CHARTS_EXCLUDE_KEY",
  RESTORE_SETTINGS: "RESTORE_SETTINGS"
};

export default SettingsActionTypes;
