const SettingsActionTypes = {
  SWITCH_CHARTS_DATE_FILTER: "SWITCH_CHARTS_DATE_FILTER",
  SET_CHARTS_FILTER_DATE: "SET_CHARTS_FILTER_DATE",
  PREV_CHARTS_FILTER_DATE: "PREV_CHARTS_FILTER_DATE",
  NEXT_CHARTS_FILTER_DATE: "NEXT_CHARTS_FILTER_DATE",
  SWITCH_CHARTS_KEY_FILTER: "SWITCH_CHARTS_KEY_FILTER",
  ADD_CHARTS_FILTER_KEY: "ADD_CHARTS_FILTER_KEY",
  DEL_CHARTS_FILTER_KEY: "DEL_CHARTS_FILTER_KEY",
  RESTORE_SETTINGS: "RESTORE_SETTINGS"
};

export default SettingsActionTypes;
