const SettingsActionTypes = {
  CHARTS_DATE_FILTER_SWITCH: "CHARTS_DATE_FILTER_SWITCH",
  CHARTS_DATE_FILTER_SET: "CHARTS_DATE_FILTER_SET",
  PREV_CHARTS_DATE_FILTER: "PREV_CHARTS_DATE_FILTER",
  NEXT_CHARTS_DATE_FILTER: "NEXT_CHARTS_DATE_FILTER",
  CHARTS_KEY_EXCLUDE_SWITCH: "CHARTS_KEY_EXCLUDE_SWITCH",
  ADD_CHARTS_EXCLUDE_KEY: "ADD_CHARTS_EXCLUDE_KEY",
  DEL_CHARTS_EXCLUDE_KEY: "DEL_CHARTS_EXCLUDE_KEY",
  RESTORE_SETTINGS: "RESTORE_SETTINGS"
};

export default SettingsActionTypes;
