export const SET_ACTIVITY_DATETIME = "SET_ACTIVITY_DATETIME";
export const SET_ACTIVITY_CATEGORY = "SET_ACTIVITY_CATEGORY";
export const SET_ACTIVITY_DETAIL = "SET_ACTIVITY_DETAIL";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";