/* const initialStateActivityNameList = [
  { name: "Reading", parent: "Work" },
  { name: "Meetings", parent: "Work" },
  { name: "Email", parent: "Work" },
  { name: "Phone Calls", parent: "Work" },
  { name: "Research", parent: "Work" },
  { name: "Discussion", parent: "Work" },
  { name: "Travel", parent: "Work" },
  { name: "Night", parent: "Sleep" },
  { name: "Nap", parent: "Sleep" },
  { name: "Breakfast", parent: "Eat" },
  { name: "Brunch", parent: "Eat" },
  { name: "Lunch", parent: "Eat" },
  { name: "Dinner", parent: "Eat" },
  { name: "Snack", parent: "Eat" },
  { name: "-", parent: "Commute" },
  { name: "-", parent: "Housework" },
  { name: "Sports", parent: "Exercise" },
  { name: "Aerobic", parent: "Exercise" },
  { name: "Strength", parent: "Exercise" },
  { name: "Books", parent: "Read" },
  { name: "Newspapers", parent: "Read" },
  { name: "Magazines", parent: "Read" },
  { name: "Internet", parent: "Read" },
  { name: "-", parent: "TV" }
]; */

const initialStateActivityNameList = [
  { name: "-", parent: "Eat" },
  { name: "Prepare", parent: "Eat" },
  { name: "Meal", parent: "Eat" },
  { name: "Snack", parent: "Eat" },
  { name: "-", parent: "Exercise" },
  { name: "Aerobic", parent: "Exercise" },
  { name: "Strength", parent: "Exercise" },
  { name: "-", parent: "Fun" },
  { name: "Game", parent: "Fun" },
  { name: "Movie", parent: "Fun" },
  { name: "Music", parent: "Fun" },
  { name: "Read", parent: "Fun" },
  { name: "Surfing", parent: "Fun" },
  { name: "Tourism", parent: "Fun" },
  { name: "TV", parent: "Fun" },
  { name: "-", parent: "Life" },
  { name: "Beauty", parent: "Life" },
  { name: "Groceries", parent: "Life" },
  { name: "Health", parent: "Life" },
  { name: "Housework", parent: "Life" },
  { name: "Hygiene", parent: "Life" },
  { name: "Prepare", parent: "Life" },
  { name: "Potty", parent: "Life" },
  { name: "Shop", parent: "Life" },
  { name: "-", parent: "Social" },
  { name: "Friend", parent: "Social" },
  { name: "Partner", parent: "Social" },
  { name: "Relative", parent: "Social" },
  { name: "-", parent: "Study" },
  { name: "Coding", parent: "Study" },
  { name: "Language", parent: "Study" },
  { name: "-", parent: "Sleep" },
  { name: "Nap", parent: "Sleep" },
  { name: "Night", parent: "Sleep" },
  { name: "-", parent: "Transport" },
  { name: "Drive", parent: "Transport" },
  { name: "Intercity", parent: "Transport" },
  { name: "Public", parent: "Transport" },
  { name: "Taxi", parent: "Transport" },
  { name: "Walk", parent: "Transport" },
  { name: "-", parent: "Work" },
  { name: "Coding", parent: "Work" },
  { name: "Contact", parent: "Work" },
  { name: "Discuss", parent: "Work" },
  { name: "Job hunting", parent: "Work" },
  { name: "Meetings", parent: "Work" },
  { name: "Planning", parent: "Work" },
  { name: "Research", parent: "Work" },
  { name: "Testing", parent: "Work" }
];

export default initialStateActivityNameList;
